name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[release theme]') }}
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          tag_prefix:

      - name: export file size
        run: |
          echo "URL=https://cdn.jsdelivr.net/gh/pzcn/IconsCDN@${{steps.tag_version.outputs.new_tag}}/lrone.tar.xz" >> ./lrone
          echo "URL=https://cdn.jsdelivr.net/gh/pzcn/IconsCDN@${{steps.tag_version.outputs.new_tag}}/explore.tar.xz" >> ./explore

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: pzcn
          author_email: pdzzzcn@gmail.com
          message: 'update theme config'
          add: "['lrone', 'explore']"

      - name: sleep
        run: sleep 10s

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPO_OWNER: pzcn
        with:
          tag_name: ${{steps.tag_version.outputs.new_tag}}
          release_name: ${{steps.tag_version.outputs.new_tag}}
          draft: false
          prerelease: false

      - name: Purge CDN
        run: |
          curl https://purge.jsdelivr.net/gh/pzcn/IconsCDN@${{steps.tag_version.outputs.new_tag}}/lrone.tar.xz
          curl https://purge.jsdelivr.net/gh/pzcn/IconsCDN@${{steps.tag_version.outputs.new_tag}}/lrone.tar.xz
