name: Update Archived Icons
on:
  push:
    paths:
      - 'addition/Icons_Archiving/**'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Archived Icons
        run: |
          cd addition/Icons_Archiving
          zip -r -9 Icons_Archiving.zip *  >/dev/null
          curl -T Icons_Archiving.zip -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/Icons_Archiving.zip?version=latest"
