name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'demo/**'
    - 'themes/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          chmod 755 ./.github/build.sh
          ./.github/build.sh
          echo version=$(echo ${{ github.event.head_commit.id }} | head -c 8) >> $GITHUB_ENV

      - name: Zip Folder
        run: |
          echo "version=${{ env.version }}" >> ./module.prop
          echo "ver=${{ env.version }}" >> ./module.prop
          XZ_OPT=-9 tar cJf icons.tar.xz ./icons
          zip -r MIUI_Icons-${{ env.version }}.zip ./common
          zip -r MIUI_Icons-${{ env.version }}.zip ./META-INF
          zip -r MIUI_Icons-${{ env.version }}.zip ./icons.tar.xz
          zip -r MIUI_Icons-${{ env.version }}.zip ./module.prop
          cp MIUI_Icons-${{ env.version }}.zip MIUI_Icons_CI_latest.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./MIUI_Icons-${{ env.version }}.zip

      - name: Pushes files
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'MIUI_Icons_CI_latest.zip'
          destination_repo: 'pzcn/IconsCDN'
          destination_folder: 'CI'
          destination_branch: 'main'
          user_email: 'pdzzzcn@gmail.com'
          user_name: 'pzcn'
          
      - name: Post to channel
        if: contains(github.event.head_commit.message, '[skip post]') == false
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FILE: ./MIUI_Icons-${{ env.version }}.zip
          COMMIT_MESSAGE: |+
            New CI version
            ChangeLog:
            *${{ github.event.head_commit.message }}* by ${{ github.event.head_commit.author.name }}
            See commit detail [here](${{ github.event.head_commit.url }})
            Get latest CI direct Link [here](https://miuiicons.vercel.app/CI/MIUI_Icons_CI_Latest.zip)
        run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v %22https%3a%2f%2fapi.telegram.org%2fbot%24%7bBOT_TOKEN%7d%2fsendMediaGroup%3fchat_id%3d%24%7bCHANNEL_ID%7d%26media%3d%5b%7b%22type%22%3a%22document%22%2c+%22media%22%3a%22attach%3a%2f%2frelease%22%2c%22caption%22%3a%24%7bESCAPED%7d%7d%2c+%22parse_mode%22%3a%22markdownv2%22%5d%22++-F+release%3d%22%40%24FILE%22
