name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'demo/**'
    - 'themes/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          chmod 755 ./.github/mtz.sh
          ./.github/mtz.sh
          echo version=$(echo ${{ github.event.head_commit.id }} | head -c 8) >> $GITHUB_ENV

      - name: Zip Folder
        run: |
          mv MIUI_Icons.zip MIUI_Icons-${{ env.version }}.zip
          mkdir push
          cp MIUI_Icons-${{ env.version }}.zip ./push/MIUI_Icons_CI_latest.zip
          cp ./.github/MIUI_Icons_Addon.zip ./push/MIUI_Icons_Addon.zip
          cp ./.github/Icons_Archiving.zip ./push/Icons_Archiving.zip

      - name: Pushes files
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        if: |
          contains(github.event.head_commit.message, 'skip') == false 
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'push/*'
          destination_repo: 'pzcn/IconsCDN'
          destination_folder: 'CI'
          destination_branch: 'main'
          user_email: 'pdzzzcn@gmail.com'
          user_name: 'pzcn'
          
      - name: send custom message
        if: contains(github.event.head_commit.message, '[skip zip]') == false
        uses: appleboy/telegram-action@master
        with:
          to: -1001198433972
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            **新的测试版本**

            ${{ github.event.head_commit.message }}
            by ${{ github.event.head_commit.author.name }}
            [下载地址](https://miuiicons.vercel.app/CI/)
            中国大陆区域无法保证连通性
          format: markdownv2