name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'demo/**'
    - 'themes/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Envs
        run: |
          echo version=$(echo ${{ github.event.head_commit.id }} | head -c 8) >> $GITHUB_ENV

      - name: Pack
        run: |
          echo "version=${{ env.version }}" >> ./addition/module/module.prop
          echo "ver=${{ env.version }}" >> ./addition/module/module.prop
          chmod 755 ./.github/pack.sh
          ./.github/pack.sh

      - name: Rename
        run: |
          mkdir output
          cp -rf ./addition/mtz/MIUI_Icons.mtz ./output/MIUI_Icons_CI_latest.mtz
          cp -rf ./addition/module/MIUI_Icons.zip ./output/MIUI_Icons_CI_latest.zip
          cp -rf ./addition/Icons_Addon/Icons_Addon.zip ./output/Icons_Addon_CI_latest.zip
          cp -rf ./addition/Icons_Archiving/Icons_Archiving.zip ./output/Icons_Archiving_CI_latest.zip
          cp -rf ./addition/module/MIUI_Icons.zip ./MIUI_Icons_${{ env.version }}.zip

      - name: Pushes files
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        if: |
          contains(github.event.head_commit.message, 'skip') == false 
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'output/*'
          destination_repo: 'pzcn/IconsCDN'
          destination_folder: 'CI'
          destination_branch: 'main'
          user_email: 'pdzzzcn@gmail.com'
          user_name: 'pzcn'
          
      - name: Post to channel
        if: contains(github.event.head_commit.message, '[skip post]') == false
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL2_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MODULE: ./MIUI_Icons_${{ env.version }}.zip
          COMMIT_MESSAGE: |+
            测试版本${{ env.version }}发布

            ${{ github.event.head_commit.message }}
            by ${{ github.event.head_commit.author.name }}
            下载链接： https://miuiicons.vercel.app/CI/
            中国大陆区域无法保证连通性
        run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://module%22,%22caption%22:${ESCAPED}%7D%5D"  -F module="@$MODULE"
