name: Update Emui Theme
on:
  workflow_dispatch:
    inputs:
      DEVICE_URL:
        description: 'THEME'
        required: true
        default: 'Aquamarine'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Update themes
        run: |
          cd emui/themes
          t=${{ github.event.inputs.THEME }}
          source $t/config.ini
          rm -rf source $t/config.ini
          XZ_OPT=-9 tar cJf $t.tar.xz $t/*
          :> icons.ini
          echo "file_size=`ls -l ./$t.tar.xz | awk '{print $5}'`" >> ./$t.ini
          echo "theme_name=$name" >> ./$t.ini
          echo "md5=`md5sum ./$t.tar.xz|cut -d ' ' -f1`" >> ./$t.ini
          echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./$t.ini
          curl -T $t.ini -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/$t.ini?version=latest"
          curl -T $t.tar.xz -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/$t.tar.xz?version=latest"