name: Update Emui Res
on:
  push:
    paths:
      - 'icons/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: mfinelli/setup-imagemagick@v1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.0.0

      - name: Convert MIUI to EMUI
        run: |
          cp -rf icons icons1 
          mkdir -p emui/icons
          cd icons1 
          rm -rf *.png
          flist=$(ls)
          for f in $flist
          do
            if test -d ./$f
            then
              cd $f
              convert 0.png -gravity center -crop 93.75%x93.75%+0+0 background.png
              rm 0.png
              convert 1.png -gravity center -crop 93.75%x93.75%+0+0 foreground.png
              rm 1.png
              cd ..
              cp -r $f ../emui/icons
            fi
          done
          cd ../emui/icons
          zip -r icons.zip *
          XZ_OPT=-9 tar cJf icons.tar.xz icons.zip
          :> icons.ini
          echo "file_size=`ls -l ./icons.tar.xz | awk '{print $5}'`" >> ./icons.ini
          echo "md5=`md5sum ./icons.tar.xz|cut -d ' ' -f1`" >> ./icons.ini
          echo "theme_name=图标包" >> ./icons.ini
          echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./icons.ini
          curl -T icons.tar.xz -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/icons.tar.xz?version=latest"
          curl -T icons.ini -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/icons.ini?version=latest"
          cd ${GITHUB_WORKSPACE}
          mkdir -p /tmp/repo
          mkdir -p /tmp/emui/update
          if [ ! -z "${{ steps.changed-files.outputs.all_changed_files }}" ];then
          mkdir /tmp/changed 
          for f in ${{ steps.changed-files.outputs.all_changed_files }}
          do
          cp --parents "./$f" /tmp/changed/
          done
          cd /tmp/changed/icons
          rm -rf *.png
          flist=$(ls)
          for f in $flist
          do
            if test -d ./$f
            then
              cd $f
              convert 0.png -gravity center -crop 93.75%x93.75%+0+0 background.png
              rm 0.png
              convert 1.png -gravity center -crop 93.75%x93.75%+0+0 foreground.png
              rm 1.png
              cd ..
              cp -r $f /tmp/emui/update
            fi
          done
          fi
          cd ${GITHUB_WORKSPACE}
          git config --global user.email sdustpedro@gmail.com
          git config --global user.name pedroz
          sha=$(git rev-parse --short HEAD)
          commit_msg="Deploy ${sha}"
          cd /tmp/repo
          remote_repo="https://${{ secrets.GIT_USERS }}:${{ secrets.GIT_TOKEN }}@e.coding.net/miuiicons/icons/emui.git"
          git clone --depth 1 $remote_repo icons
          cp -rf /tmp/emui/update/* /tmp/repo/icons
          if [ ! -z "${{ steps.changed-files.outputs.deleted_files }}" ];then
          rm -rf ${{ steps.changed-files.outputs.deleted_files }}
          fi
          cd /tmp/repo/icons
          git add .
          git commit -m "${commit_msg}" 
          git push
          cd ..
          XZ_OPT=-9 tar cJf iconsrepo.tar.xz icons
          :> iconsrepo.ini
          echo "file_size=`ls -l ./iconsrepo.tar.xz | awk '{print $5}'`" >> ./iconsrepo.ini
          echo "md5=`md5sum ./iconsrepo.tar.xz|cut -d ' ' -f1`" >> ./iconsrepo.ini
          echo "theme_name=主图标仓库" >> ./iconsrepo.ini
          echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./iconsrepo.ini
          curl -T iconsrepo.tar.xz -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/iconsrepo.tar.xz?version=latest"
          curl -T iconsrepo.ini -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/iconsrepo.ini?version=latest"
