name: Pages
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Envs
        run: |
          echo version=$(echo ${{ github.event.head_commit.id }} | head -c 8) >> $GITHUB_ENV

      - name: Get Count
        run: |
          cd icons
          echo count=$(ls -l |grep "^d"|wc -l) >> $GITHUB_ENV
          cd ..

      - name: Get Date Env
        run: |
          echo date=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d') >> $GITHUB_ENV
          echo time=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d %H:%M') >> $GITHUB_ENV

      - name: Rename
        run: |
          mkdir -p build
          sed -i "s/{ver}/${{ env.version }}/g" ./addition/pages/ci.md
          sed -i "s/{date}/${{ env.time }}/g" ./addition/pages/ci.md
          sed -i "s/{count}/${{ env.count }}/g" ./addition/pages/ci.md

      - name: html
        run: |
          sudo npm install -g markdown-styles
          generate-md --layout github --input ./addition/pages --output ./build

      - name: build to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./build