name: RELEASE

on:

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Get Date Env
        run: echo date=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d') >> $GITHUB_ENV

      - name: Get Version Env
        run: echo version=${{steps.tag_version.outputs.new_tag}} >> $GITHUB_ENV

      - name: Get Count
        run: |
          cd icons
          echo count=$(ls -l |grep "^d"|wc -l) >> $GITHUB_ENV
          cd ..

      - name: Pack
        run: |
          echo "version=${{ env.version }}" >> ./addition/module/module.prop
          echo "ver=${{ env.version }}" >> ./addition/module/module.prop
          echo "count=${{ env.count }}" >> ./addition/module/module.prop
          chmod 755 ./.github/pack.sh
          ./.github/pack.sh

      - name: Rename
        run: |
          mkdir output
          cp -rf ./addition/mtz/Default.mtz ./output/Default_${{steps.tag_version.outputs.new_tag}}.mtz
          cp -rf ./addition/mtz/Flyme9.mtz ./output/Flyme9_${{steps.tag_version.outputs.new_tag}}.mtz
          cp -rf ./addition/mtz/Explore.mtz ./output/Explore_${{steps.tag_version.outputs.new_tag}}.mtz
          cp -rf ./addition/module/MIUI_Icons.zip ./output/MIUI_Icons_${{steps.tag_version.outputs.new_tag}}.zip
          cp -rf ./addition/Icons_Addon/Icons_Addon.zip ./output/Icons_Addon_${{steps.tag_version.outputs.new_tag}}.zip
          cp -rf ./addition/Icons_Archiving/Icons_Archiving.zip ./output/Icons_Archiving_${{steps.tag_version.outputs.new_tag}}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'output/*'
          name: ${{env.date}}_${{steps.tag_version.outputs.new_tag}}
          tag_name: ${{steps.tag_version.outputs.new_tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post to channel
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL2_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FILE: |
            ./output/MIUI_Icons_${{steps.tag_version.outputs.new_tag}}.zip
          COMMIT_MESSAGE: |+
            ${{env.date}}发布${{steps.tag_version.outputs.new_tag}}版本
        run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://release%22,%22caption%22:${ESCAPED}%7D%5D"  -F release="@$FILE"
