name: test
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Update Icons
      run: |
          mkdir -p emui/update
          rm -rf icons/*.png
          flist=$(ls)
          for f in $flist; do
          do
            if test -d ./$f
            then
              cd $f
              convert 0.png -gravity center -crop 93.75%x93.75%+0+0 background.png
              rm 0.png
              convert 1.png -gravity center -crop 93.75%x93.75%+0+0 foreground.png
              rm 1.png
              cd ..
              cp -r $f ../emui/update
            fi
          done
          rm --rf icons
          git config --global user.email sdustpedro@gmail.com
          git config --global user.name pedroz
          sha=$(git rev-parse --short HEAD)
          commit_msg="Deploy ${sha}"
          remote_repo="https://${{ secrets.GIT_USERS }}:${{ secrets.GIT_TOKEN }}@e.coding.net/miuiicons/icons/emui.git"
          git clone --depth 1 $remote_repo icons
          cp -rf emui/update icons
          git add .
          git commit -m "${commit_msg}" || true
          git push || true
          cd icons
          zip -r icons.zip * >/dev/null
          XZ_OPT=-9 tar cJf iconsrepo.tar.xz icons.zip
          :> iconsrepo.ini
          echo "file_size=`ls -l ./iconsrepo.tar.xz | awk '{print $5}'`" >> ./iconsrepo.ini
          echo "md5=`md5sum ./iconsrepo.tar.xz|cut -d ' ' -f1`" >> ./iconsrepo.ini
          echo "theme_name=图标包" >> ./iconsrepo.ini
          echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./iconsrepo.ini
          curl -T iconsrepo.tar.xz -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/iconsrepo.tar.xz?version=latest"
          curl -T iconsrepo.ini -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/iconsrepo.ini?version=latest"

