name: test Update MIUI Res
on:
  push:
    paths:
      - 'icons/**'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Icons
      run: |
        mkdir -p /tmp/git_push
        cp -a -r icons/* /tmp/git_push
        cd /tmp/git_push
        git clone --depth 1 $remote_repo /tmp/dest
        rm -rf /tmp/git_push/.git
        cp -r /tmp/dest/.git/ /tmp/git_push/.git/
        cd ${GITHUB_WORKSPACE}
        mkdir -p temp/res/
        cp -rf /tmp/git_push ./temp/res/drawable-xxhdpi/
        cp -rf addition/transform_config.xml ./temp
        cd temp
        zip -r -9 icons.zip *  >/dev/null
        mv icons.zip icons
        XZ_OPT=-9 tar cJf iconsrepo.tar.xz icons 
        :> iconsrepo.ini
        echo "file_size=`ls -l ./iconsrepo.tar.xz | awk '{print $5}'`" >> ./iconsrepo.ini
        echo "md5=`md5sum ./iconsrepo.tar.xz|cut -d ' ' -f1`" >> ./iconsrepo.ini
        echo "theme_name=主图标仓库" >> ./iconsrepo.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./iconsrepo.ini
        curl -T iconsrepo.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/iconsrepo.tar.xz?version=latest"
        curl -T iconsrepo.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/iconsrepo.ini?version=latest"
        curl https://rclone.org/install.sh | sudo bash
            mkdir -p ~/.config/rclone/
            cp -rf "$GITHUB_WORKSPACE"/.github/rclone.conf ~/.config/rclone/rclone.conf
            curl -fsSL "https://nn.ci/alist.sh" | sudo bash -s install
            sudo systemctl stop alist
            echo ${{ secrets.DBBASE64 }} > base64.txt
            base64 --decode base64.txt > "$GITHUB_WORKSPACE"/db.zip
            unzip "$GITHUB_WORKSPACE"/db.zip -d "$GITHUB_WORKSPACE"
            sudo cp -f "$GITHUB_WORKSPACE"/data.db /opt/alist/data
            sudo systemctl start alist
            curl --user 'user:password' --anyauth --progress-bar -sw '%{http_code}' 'http://0.0.0.0:5244/dav/miui/' -T 'iconsrepo.tar.xz'
