name: test emui 
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Update Icons
      run: |
          rm -rf icons
          remote_repo="https://${{ secrets.GIT_USERS }}:${{ secrets.GIT_TOKEN }}@e.coding.net/miuiicons/icons/emui.git"
          git clone --depth 1 $remote_repo icons
          XZ_OPT=-9 tar cJf iconsrepo.tar.xz icons
          :> iconsrepo.ini
          echo "file_size=`ls -l ./iconsrepo.tar.xz | awk '{print $5}'`" >> ./iconsrepo.ini
          echo "md5=`md5sum ./iconsrepo.tar.xz|cut -d ' ' -f1`" >> ./iconsrepo.ini
          echo "theme_name=主图标仓库" >> ./iconsrepo.ini
          echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./iconsrepo.ini
          curl -T iconsrepo.tar.xz -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/iconsrepo.tar.xz?version=latest"
          curl -T iconsrepo.ini -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/iconsrepo.ini?version=latest"
            curl https://rclone.org/install.sh | sudo bash
            mkdir -p ~/.config/rclone/
            cp -rf "$GITHUB_WORKSPACE"/.github/rclone.conf ~/.config/rclone/rclone.conf
            curl -fsSL "https://nn.ci/alist.sh" | sudo bash -s install
            sudo systemctl stop alist
            echo ${{ secrets.DBEMUI }} > base64.txt
            base64 --decode base64.txt > "$GITHUB_WORKSPACE"/db.zip
            unzip "$GITHUB_WORKSPACE"/db.zip -d "$GITHUB_WORKSPACE"
            sudo cp -f "$GITHUB_WORKSPACE"/data.db /opt/alist/data
            sudo systemctl start alist
            rclone copy -P iconsrepo.tar.xz 123pan:/
