name: Update Res
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Update Icons
      run: |
        sha=$(git rev-parse --short HEAD)
        commit_msg="Deploy ${sha}"
        mkdir -p /tmp/git_push
        cp -a -r icons/* /tmp/git_push
        cd /tmp/git_push
        git clone --depth 1 https://${secrets.GIT_USERS}:${secrets.GIT_TOKEN}@e.coding.net/miuiicons/icons/icons.git -b MIUI /tmp/dest
        cp -r /tmp/dest/.git/ /tmp/git_push/.git/
        git add .
        git commit -m "${commit_msg}"
        git push -f origin HEAD:MIUI
        cd ${GITHUB_WORKSPACE}
        mkdir -p ./temp/res/drawable-xxhdpi/
        cp -rf /tmp/git_push/* ./temp/res/drawable-xxhdpi/
        cp -rf addition/transform_config.xml ./temp
        cd temp
        zip -r -9 icons.zip *  >/dev/null
        mv icons.zip icons
        XZ_OPT=-9 tar cJf icons.tar.xz icons
        :> icons.ini
        echo "file_size=`ls -l ./icons.tar.xz | awk '{print $5}'`" >> ./icons.ini
        echo "md5=`md5sum ./icons.tar.xz|cut -d ' ' -f1`" >> ./icons.ini
        echo "theme_name=主图标包" >> ./icons.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./icons.ini
        curl -T icons.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/icons.tar.xz?version=latest"
        curl -T icons.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/icons.ini?version=latest"
