name: sync file
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Icons
      run: |
        curl https://rclone.org/install.sh | sudo bash
        mkdir -p ~/.config/rclone/
        cp -rf "$GITHUB_WORKSPACE"/.github/rclone.conf ~/.config/rclone/rclone.conf
        curl -fsSL "https://nn.ci/alist.sh" | sudo bash -s install
        sudo systemctl stop alist
        echo ${{ secrets.DBBASE64 }} > base64.txt
        base64 --decode base64.txt > "$GITHUB_WORKSPACE"/db.zip
        unzip "$GITHUB_WORKSPACE"/db.zip -d "$GITHUB_WORKSPACE"
        sudo cp -f "$GITHUB_WORKSPACE"/data.db /opt/alist/data
        sudo systemctl start alist
        token=$(curl --user ${{ secrets.WEBDAV_PASS }} ${{ secrets.WEBDAV_LINK }})
        wget https://github.com/tickstep/aliyunpan/releases/download/v0.2.1/aliyunpan-v0.2.1-linux-amd64.zip
        unzip aliyunpan-v0.2.1-linux-amd64.zip
        cd aliyunpan-v0.2.1-linux-amd64
        ./aliyunpan login -RefreshToken=$token
        curl -o iconsrepo.tar.xz https://miuiicons-generic.pkg.coding.net/icons/files/iconsrepo.tar.xz?version=latest 
        rclone copy -P iconsrepo.tar.xz 123pan:/miui/
        ./aliyunpan upload iconsrepo.tar.xz /icons/miui
        rm -rf iconsrepo.tar.xz
        curl -o iconsrepo.tar.xz https://emuiicons-generic.pkg.coding.net/files/zip/iconsrepo.tar.xz?version=latest 
        rclone copy -P iconsrepo.tar.xz 123pan:/emui/
        ./aliyunpan upload iconsrepo.tar.xz /icons/emui
