name: test
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Icons
      run: |
        :> 111.txt
        echo 222 >> ./111.txt
        echo 222 >> ./222.txt
            curl https://rclone.org/install.sh | sudo bash
            mkdir -p ~/.config/rclone/
            cp -rf "$GITHUB_WORKSPACE"/.github/rclone.conf ~/.config/rclone/rclone.conf
            curl -fsSL "https://nn.ci/alist.sh" | sudo bash -s install
            sudo systemctl stop alist
            echo ${{ secrets.DBBASE64 }} > base64.txt
            base64 --decode base64.txt > "$GITHUB_WORKSPACE"/db.zip
            unzip "$GITHUB_WORKSPACE"/db.zip -d "$GITHUB_WORKSPACE"
            sudo cp -f "$GITHUB_WORKSPACE"/data.db /opt/alist/data
            sudo systemctl start alist
            sudo systemctl status alist
            rclone sync -P "$GITHUB_WORKSPACE"/111.txt 123pan:/miui/
            curl -T 222.txt -u user:password "http://127.0.0.1:5244/dav/"
