name: test emui 
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Update Icons
      run: |
            dd if=/dev/zero of=test.zip bs=50M count=1
            curl https://rclone.org/install.sh | sudo bash
            mkdir -p ~/.config/rclone/
            cp -rf "$GITHUB_WORKSPACE"/.github/rclone.conf ~/.config/rclone/rclone.conf
            curl -fsSL "https://nn.ci/alist.sh" | sudo bash -s install
            sudo systemctl stop alist
            echo ${{ secrets.DBEMUI }} > base64.txt
            base64 --decode base64.txt > "$GITHUB_WORKSPACE"/db.zip
            unzip "$GITHUB_WORKSPACE"/db.zip -d "$GITHUB_WORKSPACE"
            sudo cp -f "$GITHUB_WORKSPACE"/data.db /opt/alist/data
            sudo systemctl start alist
            rclone copy -P test.zip 123pan:/
