name: Update Themes
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[themes]') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          chmod 755 ./.github/themes.sh
          ./.github/themes.sh

      - name: export file size
        run: |
          cp -r ./.github/config/* ./output
          cd output
          mkdir -p .github/workflows
          mv -f main.yml .github/workflows
          echo "file_size=`ls -l ./explore.tar.xz | awk '{print $5}'`" >> ./explore
          echo "file_size=`ls -l ./lrone.tar.xz | awk '{print $5}'`" >> ./lrone
          echo "mod_date=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d')" >> ./explore
          echo "mod_date=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d')" >> ./lrone

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'output/*'
          destination_repo: 'MIUI-Adapted-Icons-Complement-Project-CDN'
          destination_folder: './'
          destination_branch: 'main'
          user_email: 'pdzzzcn@gmail.com'
          user_name: 'pzcn'
          commit_message: '[release theme]'