name: Update Themes
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[themes]') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          cd themes/explore
          XZ_OPT=-9 tar cJf explore.tar.xz *
          cd ../..
          
          cd themes/lrone
          XZ_OPT=-9 tar cJf lrone.tar.xz *
          cd ../..
          
          cd themes/luck7
          XZ_OPT=-9 tar cJf luck7.tar.xz *
          cd ../..

          cp -rf ./themes/explore/explore.tar.xz ./output
          cp -rf ./themes/lrone/lrone.tar.xz ./output
          cp -rf ./themes/luck7/luck7.tar.xz ./output

      - name: Pushes files
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'output/*'
          destination_repo: 'pzcn/IconsCDN'
          destination_folder: './'
          destination_branch: 'main'
          user_email: 'pdzzzcn@gmail.com'
          user_name: 'pzcn'