name: Update Res
on:
  push:
    paths:
      - 'themes/**'
      - 'icons/**'
      - 'addition/mtz/**'
      - 'addition/Icons_Archiving/**'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.10.1
      id: filter
      with:
        filters: |
          Icons:
            - 'icons/**'
          mtz:
            - 'addition/mtz/default/**'
          Archiving:
            - 'addition/Icons_Archiving/**'
          common:
            - 'themes/common/**'
          default:
            - 'themes/default/**'
          flyme9:
            - 'themes/flyme9/**'
          explore:
            - 'themes/explore/**'
          lrone:
            - 'themes/lrone/**'
          perfectcurve:
            - 'themes/perfectcurve/**'
          luck7:
            - 'themes/luck7/**'
          AmethystLake:
            - 'themes/AmethystLake/**'
          Aquamarine:
            - 'themes/Aquamarine/**'
          GoldenBeach:
            - 'themes/GoldenBeach/**'
          LightWings:
            - 'themes/LightWings/**'
          Nebulae:
            - 'themes/Nebulae/**'
          Reconstruction:
            - 'themes/Reconstruction/**'
          StarrySky:
            - 'themes/StarrySky/**'


    - name: Update Icons
      if: steps.filter.outputs.Icons == 'true'
      run: |
        mkdir -p ./temp/res/drawable-xxhdpi/
        cp -rf icons/* ./temp/res/drawable-xxhdpi/
        cp -rf addition/transform_config.xml ./temp
        cd temp
        zip -r -9 icons.zip *  >/dev/null
        mv icons.zip icons
        XZ_OPT=-9 tar cJf icons.tar.xz icons
        :> icons.ini
        echo "file_size=`ls -l ./icons.tar.xz | awk '{print $5}'`" >> ./icons.ini
        echo "md5=`md5sum ./icons.tar.xz|cut -d ' ' -f1`" >> ./icons.ini
        echo "theme_name=主图标包" >> ./icons.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./icons.ini
        curl -T icons.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/icons.tar.xz?version=latest"
        curl -T icons.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/icons.ini?version=latest"
    - name: Update mtz
      if: steps.filter.outputs.mtz == 'true'
      run: |
        cd addition/mtz
        XZ_OPT=-9 tar cJf mtz.tar.xz *
        :> mtz.ini
        echo "file_size=`ls -l ./mtz.tar.xz | awk '{print $5}'`" >> ./mtz.ini
        echo "md5=`md5sum ./mtz.tar.xz|cut -d ' ' -f1`" >> ./mtz.ini
        echo "theme_name=mtz资源包" >> ./mtz.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./mtz.ini
        curl -T mtz.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/mtz.tar.xz?version=latest"
        curl -T mtz.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/mtz.ini?version=latest"
    - name: Update Archiving
      if: steps.filter.outputs.Archiving == 'true'
      run: |
        cd addition/Icons_Archiving
        zip -r -9 Icons_Archiving.zip *  >/dev/null
        curl -T Icons_Archiving.zip -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/Icons_Archiving.zip?version=latest"
    - name: Update default
      if: steps.filter.outputs.default == 'true'|| steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* default
        cd default
        XZ_OPT=-9 tar cJf default.tar.xz *
        :> default.ini
        echo "file_size=`ls -l ./default.tar.xz | awk '{print $5}'`" >> ./default.ini
        echo "md5=`md5sum ./default.tar.xz|cut -d ' ' -f1`" >> ./default.ini
        echo "theme_name=MIUI经典主题包" >> ./default.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./default.ini
        curl -T default.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/default.tar.xz?version=latest"
        curl -T default.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/default.ini?version=latest"

    - name: Update flyme9
      if: steps.filter.outputs.flyme9 == 'true' || steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* flyme9
        cd flyme9
        XZ_OPT=-9 tar cJf flyme9.tar.xz *
        :> flyme9.ini
        echo "file_size=`ls -l ./flyme9.tar.xz | awk '{print $5}'`" >> ./flyme9.ini
        echo "md5=`md5sum ./flyme9.tar.xz|cut -d ' ' -f1`" >> ./flyme9.ini
        echo "theme_name=Flyme9主题包" >> ./flyme9.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./flyme9.ini
        curl -T flyme9.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/flyme9.tar.xz?version=latest"
        curl -T flyme9.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/flyme9.ini?version=latest"

    - name: Update explore
      if: steps.filter.outputs.explore == 'true' || steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* explore
        cd explore
        XZ_OPT=-9 tar cJf explore.tar.xz *
        :> explore.ini
        echo "file_size=`ls -l ./explore.tar.xz | awk '{print $5}'`" >> ./explore.ini
        echo "md5=`md5sum ./explore.tar.xz|cut -d ' ' -f1`" >> ./explore.ini
        echo "theme_name=探界主题包" >> ./explore.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./explore.ini
        curl -T explore.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/explore.tar.xz?version=latest"
        curl -T explore.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/explore.ini?version=latest"

    - name: Update lrone
      if: steps.filter.outputs.lrone == 'true'
      run: |
        cd themes/lrone
        XZ_OPT=-9 tar cJf lrone.tar.xz *
        :> lrone.ini
        echo "file_size=`ls -l ./lrone.tar.xz | awk '{print $5}'`" >> ./lrone.ini
        echo "md5=`md5sum ./lrone.tar.xz|cut -d ' ' -f1`" >> ./lrone.ini
        echo "theme_name=lrone主题包" >> ./lrone.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./lrone.ini
        curl -T lrone.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/lrone.tar.xz?version=latest"
        curl -T lrone.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/lrone.ini?version=latest"

    - name: Update perfectcurve
      if: steps.filter.outputs.perfectcurve == 'true'
      run: |
        cd themes/perfectcurve
        XZ_OPT=-9 tar cJf perfectcurve.tar.xz *
        :> perfectcurve.ini
        echo "file_size=`ls -l ./perfectcurve.tar.xz | awk '{print $5}'`" >> ./perfectcurve.ini
        echo "md5=`md5sum ./perfectcurve.tar.xz|cut -d ' ' -f1`" >> ./perfectcurve.ini
        echo "theme_name=完美曲线主题包" >> ./perfectcurve.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./perfectcurve.ini
        curl -T perfectcurve.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/perfectcurve.tar.xz?version=latest"
        curl -T perfectcurve.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/perfectcurve.ini?version=latest"

    - name: Update luck7
      if: steps.filter.outputs.luck7 == 'true'
      run: |
        cd themes/luck7
        XZ_OPT=-9 tar cJf luck7.tar.xz *
        :> luck7.ini
        echo "file_size=`ls -l ./luck7.tar.xz | awk '{print $5}'`" >> ./luck7.ini
        echo "md5=`md5sum ./luck7.tar.xz|cut -d ' ' -f1`" >> ./luck7.ini
        echo "theme_name=luck7主题包" >> ./luck7.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./luck7.ini
        curl -T luck7.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/luck7.tar.xz?version=latest"
        curl -T luck7.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/luck7.ini?version=latest"

    - name: Update AmethystLake
      if: steps.filter.outputs.AmethystLake == 'true' || steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* AmethystLake
        cd AmethystLake
        XZ_OPT=-9 tar cJf AmethystLake.tar.xz *
        :> AmethystLake.ini
        echo "file_size=`ls -l ./AmethystLake.tar.xz | awk '{print $5}'`" >> ./AmethystLake.ini
        echo "md5=`md5sum ./AmethystLake.tar.xz|cut -d ' ' -f1`" >> ./AmethystLake.ini
        echo "theme_name=EMUI-紫晶湖主题包" >> ./AmethystLake.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./AmethystLake.ini
        curl -T AmethystLake.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/AmethystLake.tar.xz?version=latest"
        curl -T AmethystLake.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/AmethystLake.ini?version=latest"
    - name: Update Aquamarine
      if: steps.filter.outputs.Aquamarine == 'true' || steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* Aquamarine
        cd Aquamarine
        XZ_OPT=-9 tar cJf Aquamarine.tar.xz *
        :> Aquamarine.ini
        echo "file_size=`ls -l ./Aquamarine.tar.xz | awk '{print $5}'`" >> ./Aquamarine.ini
        echo "md5=`md5sum ./Aquamarine.tar.xz|cut -d ' ' -f1`" >> ./Aquamarine.ini
        echo "theme_name=鸿蒙-润泽主题包" >> ./Aquamarine.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./Aquamarine.ini
        curl -T Aquamarine.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/Aquamarine.tar.xz?version=latest"
        curl -T Aquamarine.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/Aquamarine.ini?version=latest"
    - name: Update GoldenBeach
      if: steps.filter.outputs.GoldenBeach == 'true' || steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* GoldenBeach
        cd GoldenBeach
        XZ_OPT=-9 tar cJf GoldenBeach.tar.xz *
        :> GoldenBeach.ini
        echo "file_size=`ls -l ./GoldenBeach.tar.xz | awk '{print $5}'`" >> ./GoldenBeach.ini
        echo "md5=`md5sum ./GoldenBeach.tar.xz|cut -d ' ' -f1`" >> ./GoldenBeach.ini
        echo "theme_name=EMUI-碧海金沙主题包" >> ./GoldenBeach.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./GoldenBeach.ini
        curl -T GoldenBeach.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/GoldenBeach.tar.xz?version=latest"
        curl -T GoldenBeach.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/GoldenBeach.ini?version=latest"
    - name: Update LightWings
      if: steps.filter.outputs.LightWings == 'true' || steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* LightWings
        cd LightWings
        XZ_OPT=-9 tar cJf LightWings.tar.xz *
        :> LightWings.ini
        echo "file_size=`ls -l ./LightWings.tar.xz | awk '{print $5}'`" >> ./LightWings.ini
        echo "md5=`md5sum ./LightWings.tar.xz|cut -d ' ' -f1`" >> ./LightWings.ini
        echo "theme_name=EMUI-光之翼主题包" >> ./LightWings.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./LightWings.ini
        curl -T LightWings.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/LightWings.tar.xz?version=latest"
        curl -T LightWings.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/LightWings.ini?version=latest"
    - name: Update Nebulae
      if: steps.filter.outputs.Nebulae == 'true' || steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* Nebulae
        cd Nebulae
        XZ_OPT=-9 tar cJf Nebulae.tar.xz *
        :> Nebulae.ini
        echo "file_size=`ls -l ./Nebulae.tar.xz | awk '{print $5}'`" >> ./Nebulae.ini
        echo "md5=`md5sum ./Nebulae.tar.xz|cut -d ' ' -f1`" >> ./Nebulae.ini
        echo "theme_name=EMUI-宇宙之眼主题包" >> ./Nebulae.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./Nebulae.ini
        curl -T Nebulae.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/Nebulae.tar.xz?version=latest"
        curl -T Nebulae.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/Nebulae.ini?version=latest"
    - name: Update Reconstruction
      if: steps.filter.outputs.Reconstruction == 'true' || steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* Reconstruction
        cd Reconstruction
        XZ_OPT=-9 tar cJf Reconstruction.tar.xz *
        :> Reconstruction.ini
        echo "file_size=`ls -l ./Reconstruction.tar.xz | awk '{print $5}'`" >> ./Reconstruction.ini
        echo "md5=`md5sum ./Reconstruction.tar.xz|cut -d ' ' -f1`" >> ./Reconstruction.ini
        echo "theme_name=EMUI-未来之翼主题包" >> ./Reconstruction.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./Reconstruction.ini
        curl -T Reconstruction.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/Reconstruction.tar.xz?version=latest"
        curl -T Reconstruction.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/Reconstruction.ini?version=latest"
    - name: Update StarrySky
      if: steps.filter.outputs.StarrySky == 'true' || steps.filter.outputs.common == 'true'
      run: |
        cd themes
        cp -rf common/* StarrySky
        cd StarrySky
        XZ_OPT=-9 tar cJf StarrySky.tar.xz *
        :> StarrySky.ini
        echo "file_size=`ls -l ./StarrySky.tar.xz | awk '{print $5}'`" >> ./StarrySky.ini
        echo "md5=`md5sum ./StarrySky.tar.xz|cut -d ' ' -f1`" >> ./StarrySky.ini
        echo "theme_name=EMUI-星夜彩绘主题包" >> ./StarrySky.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./StarrySky.ini
        curl -T StarrySky.tar.xz -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/StarrySky.tar.xz?version=latest"
        curl -T StarrySky.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/StarrySky.ini?version=latest"

    - name: Get Env
      run: |
        echo time=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d %H:%M') >> $GITHUB_ENV
    - name: Update changelog
      run: |
        curl -skLJo old.xml https://miuiicons-generic.pkg.coding.net/icons/files/changelog.xml?version=latest
        time=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d %H:%M')
        sed -i '1d' old.xml
        :>new.xml
        cat >> new.xml << \EOF
        <?xml version="1.0" encoding="UTF-8" ?>
        <group>
        <text>
        <title>${{ env.time }}</title>
        <desc>${{ github.event.head_commit.message }}
        by ${{ github.event.head_commit.author.name }}</desc>
        <slice break="break" link="${{ github.event.head_commit.url }}" underline="underline"> 轻触查看详细内容>> </slice>
        </text>
        </group>
        EOF
        :>output.xml
        cat new.xml old.xml > output.xml
        curl -T output.xml -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/changelog.xml?version=latest"
    - name: Push changelog
      run: |
        curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{secrets.push_token}}","title":"MIUI完美图标更新了","content":"### 更新时间：${{ env.time }} \n 更新内容 \n ${{ github.event.head_commit.message }} \n by ${{ github.event.head_commit.author.name }} \n ### 您现在可以前往MIUI完美图标APP进行更新","topic":"MIUI"}' http://www.pushplus.plus/send
