name: Update All
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Update
          run: |
            chmod 755 ./.github/updateall.sh
            ./.github/updateall.sh