name: Update Res
on:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.10.1
      id: filter
      with:
        filters: |
          Icons:
            - 'icons/**'
          default:
            - 'addition/default/**'
          flyme9:
            - 'themes/flyme9/**'
          explore:
            - 'themes/explore/**'
          lrone:
            - 'themes/lrone/**'
          perfectcurve:
            - 'themes/perfectcurve/**'
          luck7:
            - 'themes/luck7/**'

    - name: Update Icons
      if: steps.filter.outputs.Icons == 'true'
      run: |
        mkdir -p ./temp/res/drawable-xxhdpi/
        cp -rf icons/* ./temp/res/drawable-xxhdpi/
        cp -rf addition/default/transform_config.xml ./temp
        cd temp
        zip -r -9 icons.zip *  >/dev/null
        mv icons.zip icons
        XZ_OPT=-9 tar cJf icons.tar.xz icons
        :> icons.ini
        echo "file_size=`ls -l ./icons.tar.xz | awk '{print $5}'`" >> ./icons.ini
        echo "md5=`md5sum ./icons.tar.xz|cut -d ' ' -f1`" >> ./icons.ini
        echo "theme_name=主图标包" >> ./icons.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./icons.ini
        cd ..
        mkdir ./output
        cp -rf ./temp/icons.tar.xz ./output
        cp -rf ./temp/icons.ini ./output

    - name: Update default
      if: steps.filter.outputs.default == 'true'
      run: |
        cd addition/default
        XZ_OPT=-9 tar cJf default.tar.xz *
        :> default.ini
        echo "file_size=`ls -l ./default.tar.xz | awk '{print $5}'`" >> ./default.ini
        echo "md5=`md5sum ./default.tar.xz|cut -d ' ' -f1`" >> ./default.ini
        echo "theme_name=MIUI经典主题包" >> ./default.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./default.ini
        cd ../..
        mkdir ./output
        cp -rf ./addition/default/default.tar.xz ./output
        cp -rf ./addition/default/default.ini ./output

    - name: Update flyme9
      if: steps.filter.outputs.flyme9 == 'true'
      run: |
        cd themes/flyme9
        XZ_OPT=-9 tar cJf flyme9.tar.xz *
        :> flyme9.ini
        echo "file_size=`ls -l ./flyme9.tar.xz | awk '{print $5}'`" >> ./flyme9.ini
        echo "md5=`md5sum ./flyme9.tar.xz|cut -d ' ' -f1`" >> ./flyme9.ini
        echo "theme_name=Flyme9主题包" >> ./flyme9.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./flyme9.ini
        cd ../..
        mkdir ./output
        cp -rf ./themes/flyme9/flyme9.tar.xz ./output
        cp -rf ./themes/flyme9/flyme9.ini ./output

    - name: Update explore
      if: steps.filter.outputs.explore == 'true'
      run: |
        cd themes/explore
        XZ_OPT=-9 tar cJf explore.tar.xz *
        :> explore.ini
        echo "file_size=`ls -l ./explore.tar.xz | awk '{print $5}'`" >> ./explore.ini
        echo "md5=`md5sum ./explore.tar.xz|cut -d ' ' -f1`" >> ./explore.ini
        echo "theme_name=探界主题包" >> ./explore.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./explore.ini
        cd ../..
        mkdir ./output
        cp -rf ./themes/explore/explore.tar.xz ./output
        cp -rf ./themes/explore/explore.ini ./output

    - name: Update lrone
      if: steps.filter.outputs.lrone == 'true'
      run: |
        cd themes/lrone
        XZ_OPT=-9 tar cJf lrone.tar.xz *
        :> lrone.ini
        echo "file_size=`ls -l ./lrone.tar.xz | awk '{print $5}'`" >> ./lrone.ini
        echo "md5=`md5sum ./lrone.tar.xz|cut -d ' ' -f1`" >> ./lrone.ini
        echo "theme_name=MIUI经典主题包" >> ./lrone.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./lrone.ini
        cd ../..
        mkdir ./output
        cp -rf ./themes/lrone/lrone.tar.xz ./output
        cp -rf ./themes/lrone/lrone.ini ./output

    - name: Update perfectcurve
      if: steps.filter.outputs.perfectcurve == 'true'
      run: |
        cd themes/perfectcurve
        XZ_OPT=-9 tar cJf perfectcurve.tar.xz *
        :> perfectcurve.ini
        echo "file_size=`ls -l ./perfectcurve.tar.xz | awk '{print $5}'`" >> ./perfectcurve.ini
        echo "md5=`md5sum ./perfectcurve.tar.xz|cut -d ' ' -f1`" >> ./perfectcurve.ini
        echo "theme_name=MIUI经典主题包" >> ./perfectcurve.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./perfectcurve.ini
        cd ../..
        mkdir ./output
        cp -rf ./themes/perfectcurve/perfectcurve.tar.xz ./output
        cp -rf ./themes/perfectcurve/perfectcurve.ini ./output

    - name: Update luck7
      if: steps.filter.outputs.luck7 == 'true'
      run: |
        cd themes/luck7
        XZ_OPT=-9 tar cJf luck7.tar.xz *
        :> luck7.ini
        echo "file_size=`ls -l ./luck7.tar.xz | awk '{print $5}'`" >> ./luck7.ini
        echo "md5=`md5sum ./luck7.tar.xz|cut -d ' ' -f1`" >> ./luck7.ini
        echo "theme_name=MIUI经典主题包" >> ./luck7.ini
        echo "theme_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./luck7.ini
        cd ../..
        mkdir ./output
        cp -rf ./themes/luck7/luck7.tar.xz ./output
        cp -rf ./themes/luck7/luck7.ini ./output
        
    - name: Pushes files
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'output/.'
        destination_repo: 'pzcn/IconsCDN'
        destination_folder: './'
        destination_branch: 'main'
        user_email: 'pdzzzcn@gmail.com'
        user_name: 'pzcn'